### ISSUE TITLE
Failed to start the backend

### ISSUE THREAD

**Issue by EyesNakazawa** [langchain-ai/opengpts#219]
◆ Premise
I am using the following environment:
Redis server:
　Version 7.2.4
　Running on Ubuntu on WSL
　RediSearch v2.6 installed
　Communication with Windows side confirmed via redis-cli
Backend:
　Used as is, cloned from git on 24/3/10
　Running on Windows 11

◆ Advice Requested
I am encountering the following error when starting the backend. Do you know how to resolve it?

◆ Error
INFO:     Uvicorn running on http://127.0.0.1:8100/ (Press CTRL+C to quit)
INFO:     Started reloader process [25808] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 68, in serve
    config.load()
  File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\config.py", line 467, in load
    self.loadedapp = import_from_string(self.app)
  File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\importlib_init.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in call_with_frames_removed
  File "C:\Users\itita\Desktop\bakend\app\server.py", line 9, in <module>
    from app.api import router as api_router
  File "C:\Users\itita\Desktop\bakend\app\api_init.py", line 3, in <module>
    from app.api.assistants import router as assistants_router
  File "C:\Users\itita\Desktop\bakend\app\api\assistants.py", line 7, in <module>
    import app.storage as storage
File "C:\Users\itita\Desktop\bakend\app\storage.py", line 10, in <module>
    from app.agent import AgentType, get_agent_executor
  File "C:\Users\itita\Desktop\bakend\app\agent.py", line 24, in <module>
    from app.tools import (
  File "C:\Users\itita\Desktop\bakend\app\tools.py", line 184, in <module>
    v()
  File "C:\Users\itita\Desktop\bakend\app\tools.py", line 129, in getaction_server
    toolkit = ActionServerToolkit(
  File "C:\Users\itita\AppData\Local\Programs\Python\Python310\lib\site-packages\pydantic\v1\main.py", line 341, in __init
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for ActionServerToolkit
url
  none is not an allowed value (type=type_error.none.not_allowed)
api_key
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by mkorpela** [comment]
@EyesNakazawa thank you for reporting the issue. New version on `main` now has a different way to initialise ActionServerToolkit. This should fix the problem you have described.

Closing the issue. Feel free to comment on the issue if the problem persists.
