### ISSUE TITLE
redis.exceptions.ResponseError: opengpts: no such index

### ISSUE THREAD

**Issue by growmuye** [langchain-ai/opengpts#93]

**Comment by StefanGalissie** [comment]
Hi there, I'm encountering a similar problem while attempting to utilize OpenGPT's Retriever feature. The AI understand the query, acknowledging the use of Retriever, but an error arises afterward.

Here are the details:

backend_1   | INFO:     Started server process [1]
backend_1   | INFO:     Waiting for application startup.
backend_1   | INFO:     Application startup complete.
backend_1   | INFO:     Uvicorn running on http://0.0.0.0:8100 (Press CTRL+C to quit)
backend_1   | INFO:     172.18.0.1:33090 - "GET / HTTP/1.1" 200 OK
backend_1   | INFO:     172.18.0.1:33090 - "GET /assets/index-86d2f9e8.css HTTP/1.1" 200 OK
backend_1   | INFO:     172.18.0.1:33106 - "GET /assets/index-338f04a9.js HTTP/1.1" 200 OK
backend_1   | INFO:     172.18.0.1:33106 - "GET /runs/config_schema HTTP/1.1" 200 OK
backend_1   | INFO:     172.18.0.1:33122 - "GET /assistants/public/ HTTP/1.1" 200 OK
backend_1   | INFO:     172.18.0.1:33090 - "GET /threads/ HTTP/1.1" 200 OK
backend_1   | INFO:     172.18.0.1:33138 - "GET /assistants/ HTTP/1.1" 200 OK
backend_1   | INFO:     172.18.0.1:33122 - "GET /favicon.ico HTTP/1.1" 404 Not Found
backend_1   | INFO:     172.18.0.1:41224 - "PUT /assistants/f427e8cc-996c-4542-b75f-bd1619565940 HTTP/1.1" 200 OK
backend_1   | INFO:     172.18.0.1:41240 - "POST /ingest HTTP/1.1" 500 Internal Server Error
backend_1   | ERROR:    Exception in ASGI application
backend_1   | Traceback (most recent call last):
backend_1   |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run             _asgi
backend_1   |     result = await app(  # type: ignore[func-returns-value]
backend_1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(...)
backend_1   |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 524, in read_response
backend_1   |     raise response
backend_1   | redis.exceptions.ResponseError: opengpts: no such index
backend_1   | INFO:     172.18.0.1:56516 - "GET /threads/0195c545-d488-48c7-86a6-92ad33bf22be/messages HTTP/1.1" 20

**Comment by world4jason** [comment]
same here, is this solved?

**Comment by world4jason** [comment]
https://github.com/langchain-ai/opengpts/issues/154#issuecomment-1923143411

solved, workaround lol

**Comment by StefanGalissie** [comment]
Solved also on my side. It was a UFT-8 encoding issue in my input document. Removing non UFT-8 characters have solved the issue.
